name: Build
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALCHEMY_KEY: '${{secrets.ALCHEMY_KEY}}'
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.0.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Compilation
        run: 'npm run compile'
      - name: Tests
        run: 'npm run test'
      - name: Fork Tests
        run: 'npm run test-fork'